plugins {
    id 'org.springframework.boot'
}

description = 'module-api'

ext {
    set('springAiVersion', '2.0.1')
}

dependencies {
    implementation project(':core')
    implementation project(':infra')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'

    // Data
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-elasticsearch'
    implementation 'io.github.openfeign.querydsl:querydsl-jpa:7.5'

    // Kafka
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    // AI
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
//    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    // 현재 코드가 Jackson 2 패키지를 직접 import함
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // JWT
    implementation 'com.nimbusds:nimbus-jose-jwt'

    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'com.mysql:mysql-connector-j'

    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-elasticsearch-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-websocket-test'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}
