global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "module-batch-docker"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["batch:9091"]

  - job_name: "module-batch-local"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:9091"]
