plugins {
    id 'java-library'
}

ext {
    set('springAiVersion', '2.0.1')
}

dependencies {
    implementation project(':core')

    // Database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // ContentEmbeddingDocument 어노테이션용
    api 'org.springframework.data:spring-data-elasticsearch'

    // MVC, Interceptor, ExceptionHandler
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // External API HTTP client
    implementation 'org.springframework.boot:spring-boot-starter-restclient'

    // Jakarta Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // LoggingAspect
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'

    // RedisConfig, ErrorResponse
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // QueryDSL 실행
    implementation 'io.github.openfeign.querydsl:querydsl-jpa:7.5'

    // Swagger / OpenAPI
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.1'

    // AWS S3
    implementation platform('software.amazon.awssdk:bom:2.54.3')
    implementation 'software.amazon.awssdk:s3'

    // AI
    api 'org.springframework.ai:spring-ai-starter-model-google-genai:2.0.1'
    api 'org.springframework.ai:spring-ai-starter-model-google-genai-embedding:2.0.1'
    api 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-redis:2.0.1'

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

