INSTANCE_ID: api-local-1

spring:
  config:
    activate:
      on-profile: dev

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: com.codeit.modoo_playlist.infra.event.kafka,com.codeit.modoo_playlist.infra.event


module-api:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_SECRET:local-development-access-secret-at-least-32-bytes}
    refresh-token:
      secret: ${JWT_REFRESH_SECRET:local-development-refresh-secret-at-least-32-bytes}
  auth:
    cookie:
      secure: false
