spring:
  config:
    activate:
      on-profile: dev

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: com.codeit.modoo_playlist.infra.event.kafka


module-api:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_SECRET:local-development-access-secret-at-least-32-bytes}
    refresh-token:
      secret: ${JWT_REFRESH_SECRET:local-development-refresh-secret-at-least-32-bytes}
  auth:
    cookie:
      secure: false